name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.22

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Nix Flake Checker
        uses: DeterminateSystems/flake-checker-action@v11

      - name: Check Nixvim Configuration
        run: nix flake check .

  format-lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.22

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Nix Linting and Formatting Tools
        run: nix-env -i statix nixfmt-rfc-style -f '<nixpkgs>'

      - name: Run Statix Lint
        run: statix fix

      - name: Run Nix Format
        run: nix fmt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: auto lint/format'

  success:
    runs-on: ubuntu-latest
    needs:
      - build
      - format-lint
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}

